name: Backup R Packages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**/install_dependencies.R'

jobs:
  sync-r-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Source Repo (FigureYa)
        uses: actions/checkout@v4
        with:
          path: source-repo

      - name: Checkout Target Repo (FigureYa-package)
        uses: actions/checkout@v4
        with:
          repository: ying-ge/FigureYa-package
          path: target-repo
          token: ${{ secrets.FIGUREYA2ACTION }}

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'

      # 修正此步骤的 YAML 语法
      - name: Install R script dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            dplyr
            stringr
            purrr
            httr
            remotes

      - name: Run R script to collect and download packages
        run: Rscript source-repo/.github/scripts/collect_and_download.R

      - name: Commit and Push downloaded packages
        run: |
          cd target-repo
          if [[ -z $(git status --porcelain) ]]; then
            echo "没有新的或更新的包，无需提交。"
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "自动更新 R 源码包"
          git push
